---
title: "Semesterproject_paper"
author: "Lisa Wahlen"
date: "`r Sys.Date()`"
output: html_document
---

Length of report (approx. 15000 char (incl. spaces, incl. References list, excl. Code listing), 20000 char max)

```{r setup, include=FALSE}

# had to install Rtools43 before i could run the code below : https://cran.rstudio.com/bin/windows/Rtools/rtools43/rtools.html

# devtools::install_github("benmarwick/wordcountaddin",  type = "source", dependencies = TRUE)
# wordcountaddin:::text_stats() # to check character count
# install.packages("koRpus")

library(wordcountaddin)
library(koRpus)

wordcountaddin:::text_stats()
```

## Abstract

## Introduction
As mountainbiking is a popular sport in Switzerland (Fischer et al., 2021), both environmental and policy issues arise (Pröbstl-Haider et al., 2018). It is deemed necessary to find a way to not only meet the requirements of bikers and hikers but also of nature. In order to be able to talk about these issues on an objective level, it could be of interest to find out more about mountainbiking from a spatial use and movement based perspective. 
In this project, we aim at filtering mountainbiking movement patterns in crowdsourced movement data according to specific movement criteria which should only apply to mountianbikers.

In this project, we aim at defining criteria that indicate mountainbiking movement patterns, and try to provide information about the characteristics of mountainbiking. 

what are characteristics of mountainbiking? -> downhill (not uphill), in vegetated areas / trails (not on streets), within a certain speed range. 

## Research Question
In this paper we will work on the following two research questions: 
- With which criteria can we filter a downhill oriented mountainbiking movement pattern from Posmo data? 
- Is this combination of criteria applicable to all our data?


## Data and Methods

### Datasets

For our project, we used the movement trajectories that were created by Lisa Wahlen when going mountainbiking. The trajectories were recorded by using the GPS-tracking App posmo (Genossenschaft Posmo Schweiz, 2022) with a sampling rate of 10 seconds. Lisa completed 6 mountainbiking tours in the period from the 4th of May to the 18th of May 2023. All tours except for one were done in Switzerland in the areas of Allmiried (Diemtigtal), Valbirse and Solothurn. One tour was tracked in Germany, near Todtnau. 

For the assessment of the criteria that describe the movement pattern of mountain biking, we used the MOPUBE vector dataset providing the land cover types of the canton of Bern (Amt für Geoinformation des Kantons Bern, 2023). In addidtion, we worked with parts of the swiss digital terrain model swissALTI3D (Bundesamt für Landestopografie swisstopo, 2022). This elevation data is provided as raster in a resolution of 0.5 m in grids of 1 km2.

We chose the tour Lisa made on the 18th of May in Allmiried to define the characteristics of the biking movement pattern and tried to apply the criteria to the tours of XXX and YYY for verification. The Allmiried trajectory also included the car ride from Solothurn to the biking location and back. A first visualisation of transport modes of the data revealed that most of the mountainbiking part of the trajectory was labelled as "car" in by the posmo app. 

**To filter the movement pattern of mountainbiking we further used the following data: 

- posmo trajectories: sampling rate, 10 s
- SwissAlti3D: This elevation data is provided by the government of switzerland in a resolution of 0.5 m. It is provided in grids of 1 km2 for all of Switzerland as bot a .tif file and a .xyz file. For the project here, we used the .tif files.
- MOPUBE BBF: Ground type of the canton of Bern**

### Preprocessing

The Allmiried table was first converted to a georeferenced sf feature. A temporal outlier recorded the night before the trip started was removed, as well as unnecessary or redundant information about Lisa's user ID, the weekday, or the place name.

Preprocessing Bodenbedeckung?

Preprocessing swissALTI3D?

### Methods
In order to filter the mountainbiking pattern, we defined three criteria with which we should be able to have a unique identifier. Those three criteria consist of the speed with which the person is moving, the groundtype on which the trajectory is laying and furthermore the steepness of the trajectory, which needs to be directed downhill. 
Using just one or two of the criteria will always still allow for other activities. Such that a trajectory placed on grass and in forests could still also be a hiker, which also applies to the downhill movement. The Speed of a mountainbiker is hard to define, but it is also not a unique identifier for this movement pattern. 

#### Speed

For every fix on the trajectory we calculated the average speed within the window of four neighboring points, similar to the moving window method of Laube & Purves (2011). The euclidean distance to the two points before and the two points after the fix was calculated and divided by the time difference between the fix and the two points before and after, respectively. Fixes where the speed calculation could not be completed because either the distance or the time between two points was 0, were regarded as static. 80 points were labelled as static, and used for segmentation of the trajectory. They were located in places on the trajectory where little movement or a change in transport mode is plausible (e.g. at the bottom and the top of the cable car allmiried, somewhere in the middle of the downhill trail, at train stations in Solothurn).

The extraction of the mountainbiking parts of the trajectory was based on visual assessment of the movement parameter profile (Dodge et al., 2009) for the average speed, and selection of the relevant segments. The selected moving segments included the cable car Lisa took to get to the trail start.
To isolate the cable car and determine the relevant speed range for mounainbiking, the average speed distribution of the selected segments was calculated. The speed values that best characterized the movement of mountain biking were identified through a process of testing.


#### Groundtype


#### Steepness

#### Combination of all criteria

### Limitations
- we should try our code on another mountainbike pattern from Lisa to find whether its applicable to all patterns. 

## Results

### Speed
The average Speed on the Allmiried tour was 37.33548 km/h. The biking segments (including the cable car) showed an average speed of 7.80428 km/h. Since Lisa took the cable car several times on the Allmiried tour, the second and the third quartile of the speed distribution represent the speed of the cable car. In consequence, the first and the fourth quartile of the distribution were chosen to represent mountainbiking, resulting in a range of speed values from 0 to 2.855 and from 10.308 to 26.95490. These criteria also preserve the transport mode "walking".

## Discussion

## References

APA 7th edition instructions: <https://libguides.jcu.edu.au/apa/books#s-lg-box-21191622>

Amt für Geoinformation des Kantons Bern. (2023). *Amtliche Vermessung vereinfacht* [Map].  2023https://www.agi.dij.be.ch/de/start/geoportal/geodaten/detail.html?type=geoproduct&code=MOPUBE

Bundesamt für Landestopografie swisstopo. (2022). *swissALTI3D: das hochaufgelöste Terrainmodell der Schweiz* [Map]. https://www.swisstopo.admin.ch/de/geodata/height/alti3d.html

Dodge, S., Weibel, R., & Forootan, E. (2009). Revealing the physics of movement: Com-
paring the similarity of movement characteristics of different types of moving objects.
*Computers, Environment and Urban Systems, 33*(6), 419–434. https://doi.org/10.1016/j.compenvurbsys.2009.07.008

Fischer, A., Lamprecht, M., & Bürgi, R. (2021). *Mountainbiken in der
Schweiz 2020: Auswertung Mountainbikeland-Befragung 2019
und Sekundäranalyse von «Sport Schweiz 2020»*. Bundesamt für Strassen ASTRA und Stiftung
SchweizMobil. https://www.astra.admin.ch/astra/de/home/themen/langsamverkehr/materialien.html

Genossenschaft Posmo Schweiz. (2022). *Posmo Project App - Tracking für Gruppen*. https://posmo.coop/produkte/posmo-project-tracking-fuer-gruppen

Laube, P. (2014). *Computational Movement Analysis*. Springer Cham. <https://doi.org/10.1007/978-3-319-10268-9>

Laube, P. & Purves, R.(2011) How fast is a cow? Cross-scale Analysis of Movement Data, *Transactions in GIS, 15*(3), 401–418, John Wiley & Sons Ltd, DOI:
10.1111/j.1467-9671.2011.01256.x

***Dodge, S., Laube, P., & Weibel, R. (2012). Movement similarity assessment using symbolic representation of trajectories. *International Journal of Geographical Information Science, 26*(9), 1563-1588. https://doi.org/10.1080/13658816.2011.630003***

Pröbstl-Haider, U., Lund-Durlacher, D., Antonschmidt, H. & Hödl, C. (2018). Mountain bike tourism in Austria and the Alpine region – towards a sustainable model for multi-stakeholder product development. *Journal of Sustainable Tourism, 26*(4), 567-582. https://doi.org/10.1080/09669582.2017.1361428

